package constants

const OPEN_STATUS = "OPEN"
const MERGED_STATUS = "MERGED"
const TEAM_EXISTS = "TEAM_EXISTS"
const TEAM_EXISTS_TEXT = "%s already exists"
const USER_EXISTS = "USER_EXISTS"
const USER_EXISTS_TEXT = "some of users already exists"
const PR_EXISTS = "PR_EXISTS"
const PR_EXISTS_TEXT = "PR id already exists"
const PR_MERGED = "PR_MERGED"
const PR_MERGED_TEXT = "cannot reassign on merged PR"
const NOT_ASSIGNED = "NOT_ASSIGNED"
const NOT_ASSIGNED_TEXT = "reviewer is not assigned to this PR"
const NO_CANDIDATE = "NO_CANDIDATE"
const NO_CANDIDATE_TEXT = "no active replacement candidate in team"
const NOT_FOUND = "NOT_FOUND"
const NOT_FOUND_TEXT = "resource not found"
const BAD_BODY = "BAD_BODY"
const BAD_BODY_TEXT = "bad body response"

const PG_ERROR_CODE = "23505"
