package constants

const OPEN_STATUS = "OPEN"
const MERGED_STATUS = "MERGED"
const TEAM_EXISTS = "TEAM_EXISTS"
const USER_EXISTS = "USER_EXISTS"
const PR_EXISTS = "PR_EXISTS"
const PR_MERGED = "PR_MERGED"
const NOT_ASSIGNED = "NOT_ASSIGNED"
const NO_CANDIDATE = "NO_CANDIDATE"
const NOT_FOUND = "NOT_FOUND"
